packages:
  - 'code-scanning'
  - 'common'
  - 'get-changed-files'
  - 'pr-filter'
  - 'send-teams-notification'
  - 'validate-lock-files'
  - 'validate-node-versions'
  - 'verify-version-change'

catalog:
  "@actions/core": 1.11.1
  "@actions/exec": 1.1.1
  "@actions/github": 6.0.1
  "@types/jest": ^29.5.12
  "@types/node": ^16.18.105
  "@vercel/ncc": ^0.38.1
  "rimraf": ^3.0.2
  "ts-jest": ^29.2.4
  typescript: ^4.9.5