name: validate-sbom
description: Install CycloneDX CLI and validate SBOM file(s)

inputs:
  input-format:
    description: SBOM file format
    required: false
    default: json
  input-file:
    description: Path to SBOM file to validate
    required: false
  input-files:
    description: Newline, comma, or semicolon separated paths to SBOM files to validate
    required: false

runs:
  using: node24
  main: dist/index.js
