name: pnpm Audit
description: A GitHub Action to run pnpm audit and report vulnerabilities

inputs:
  target:
    type: string
    description: The root path of the repository to audit
    required: true

  artifacts:
    type: string
    description: The path to the artifacts folder where reports will be saved
    required: true

  config:
    type: string
    description: JSON5 configuration object for the audit
    required: false
    default: '{}'

runs:
  using: node20
  main: dist/index.js
