name: install-internal-package
description: Installs internal devextreme and devextreme-dist packages

inputs:
  install-dist:
    description: true to install the internal devextreme and devextreme-dist packages; false to install the internal devextreme package only
    required: false
    default: false
  working-directory:
    description: path to the directory where the target package.json is located
    required: false
    default: './'

runs:
  using: composite
  defaults:
    run:
      shell: bash
      working-directory: ${{ inputs.working-directory }}
  steps:
    - name: Authenticate to GitHub Packages
      run: npm set //npm.pkg.github.com/:_authToken="${{ github.token }}"

    - name: Determine DevExtreme Version
      id: devextreme_version
      run: echo "version=$(npm pkg get dependencies.devextreme --workspaces=false | tr -d '"')" >> $GITHUB_OUTPUT

    - name: Download Internal devextreme Package
      id: download_devextreme_package
      run: |
        npm pack @devexpress/devextreme-internal@${{ steps.devextreme_version.outputs.version }} --registry https://npm.pkg.github.com
        echo "dxtfilename=$(find . -name devexpress-devextreme-internal-*.tgz)" >> $GITHUB_OUTPUT

    - name: Check if DevExtreme File is Downloaded
      if: steps.download_devextreme_package.outputs.dxtfilename == ''
      run: exit 1

    - name: Install Internal devextreme Package
      run: npm i devextreme@${{ steps.download_devextreme_package.outputs.dxtfilename }}

    - name: Download Internal devextreme-dist Package
      if: inputs.install-dist
      id: download_devextreme_dist_package
      run: |
        npm pack @devexpress/devextreme-dist-internal@${{ steps.devextreme_version.outputs.version }} --registry https://npm.pkg.github.com
        echo "dxtdistfilename=$(find . -name devexpress-devextreme-dist-internal-*.tgz)" >> $GITHUB_OUTPUT

    - name: Check if DevExtreme-Dist File is Downloaded
      if: inputs.install-dist && steps.download_devextreme_dist_package.outputs.dxtdistfilename == ''
      run: exit 1

    - name: Install Internal devextreme-dist Package
      if: inputs.install-dist
      run: npm i devextreme-dist@${{ steps.download_devextreme_dist_package.outputs.dxtdistfilename }}
