name: Notify Teams
description: Send Teams notifications

inputs:
  hook_url:
    description: 'URL of MS Teams hook'
    required: false
  bearer_token:
    description: 'Github token'
    required: false
  only_on_push:
    description: 'Enable on push event only'
    default: 'true'
    required: false
  specific_repo:
    description: 'Filter by repository name (format: `organization/repository`)'
    required: false
  specific_branch:
    description: 'Filter by branch name'
    required: false
  alerts:
    description: 'Alerts JSON array'
    required: false
  alert_type:
    description: 'Alerts type (CodeQL, Dependabot)'
    default: 'CodeQL'
    required: false
  alerts_cache_file:
    description: 'Alerts cache file name'
    default: 'notify.json'
    required: false

runs:
  using: node20
  main: dist/index.js
