name: Publish Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: publish-actions

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and place publishable artifacts
        run: pnpm dist

      - name: Publish to release-actions branch
        env:
          BRANCH: release-actions
          SHA: ${{ github.sha }}
          GIT_USER_NAME: ${{ github.actor }}
          GIT_USER_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          ACTION_DIRS: |
            get-changed-files
            pr-filter
            send-teams-notification
            validate-sbom
            verify-version-change
            install-internal-package
            lgtm
            validate-lock-files
            validate-node-versions
            pnpm-audit
          WORKFLOW_FILES: repository-check.yml
        run: ./scripts/publish-actions.sh
