name: Repository Check

on:
  workflow_call:
    inputs:
      config:
        type: string
        description: 'JSON5 configuration object (e.g. { ignoredAdvisories: ["GHSA-..."] })'
        required: false
        default: '{}'

jobs:
  repo-check:
    name: Repository Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Validate lock files
        uses: DevExpress/github-actions/validate-lock-files@repository-check
        with:
          target: .
          artifacts: artifacts

      - name: Validate Node versions
        uses: DevExpress/github-actions/validate-node-versions@repository-check
        with:
          target: .
          artifacts: artifacts

      - name: Check pnpm audit
        uses: DevExpress/github-actions/pnpm-audit@repository-check
        with:
          target: .
          artifacts: artifacts
          config: ${{ inputs.config }}

      - name: Upload validation results
        uses: actions/upload-artifact@v4
        with:
          name: health-check
          path: artifacts/*.json
          if-no-files-found: error
